[package]
name = "mmv"
version = "0.1.5"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
regex = "1.4.1"
structopt = "0.3.20"
walkdir = "2.3.1"
